name: Deploy Pages

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:

      - name: Checkout

        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

        with:

          version: 7

      - name: Install dependencies

        run: |

         node _worker.js
